# Generated by Django 5.2.9 on 2025-12-17 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_listitem_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listitem_set', to='checklist.sections'),
        ),
    ]
