# Generated by Django 5.2.9 on 2025-12-17 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_listitem_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checklistprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='checklistprogress',
            name='stream',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='checklistprogress',
            unique_together={('items', 'user', 'stream')},
        ),
    ]
