# Generated by Django 5.2.9 on 2025-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('checklist', '0004_alter_checklistprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='checklist_roles',
            field=models.ManyToManyField(blank=True, help_text='Roles this user can perform in checklists', related_name='users', to='checklist.role', verbose_name='Checklist Roles'),
        ),
    ]
