# Generated by Django 5.2.9 on 2025-12-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningMS', '0002_alter_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='outcomes',
            field=models.JSONField(default=list, help_text='Learning outcomes of this course'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title',)},
        ),
    ]
