# Generated by Django 5.2.9 on 2025-12-16 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningMS', '0003_course_outcomes_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
