# Generated by Django 5.2.9 on 2025-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningMS', '0004_alter_course_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
