# Generated by Django 5.2.9 on 2025-12-29 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('course', 'order')},
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('submitted_review', 'Submitted Review'), ('uploaded', 'Uploaded'), ('created', 'Created')], max_length=50)),
                ('target_type', models.CharField(help_text='Model name of the target (e.g. Course, Lesson, Assessment)', max_length=100)),
                ('target_id', models.PositiveIntegerField(help_text='Primary key of the target object')),
                ('target_name', models.CharField(help_text='Human-readable name for fast display', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='lms_activit_created_223787_idx'), models.Index(fields=['action'], name='lms_activit_action_739904_idx'), models.Index(fields=['target_type', 'target_id'], name='lms_activit_target__6949de_idx')],
            },
        ),
    ]
