# Generated by Django 5.2.9 on 2025-12-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_review_status_alter_lesson_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_answer',
            field=models.CharField(blank=True),
        ),
    ]
