# Generated by Django 5.2.9 on 2025-12-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_answer_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user_answer',
        ),
    ]
