# Generated by Django 5.2.9 on 2026-01-02 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_remove_answer_user_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['lesson']},
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='progress_value',
            field=models.FloatField(default=0.0, help_text='Progress percentage (0.0 to 100.0)'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='session_data',
            field=models.JSONField(default=dict, help_text='Stores optional metadata like video seconds watched, PDF time spent, scroll %'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
