# Generated by Django 5.2 on 2025-07-17 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View')], max_length=20)),
                ('table_name', models.CharField(help_text='Name of the database table affected', max_length=100)),
                ('record_id', models.CharField(blank=True, help_text='ID of the affected record', max_length=100, null=True)),
                ('changes', models.JSONField(blank=True, help_text='Details of changes made (for UPDATE actions)', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('additional_info', models.TextField(blank=True, help_text='Additional context or details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'action'], name='logs_system_user_id_0e0614_idx'), models.Index(fields=['table_name', 'timestamp'], name='logs_system_table_n_ca018a_idx')],
            },
        ),
    ]
